# Filter Dataset Records Using Pandas

## Veda Technology – AI/ML Internship Task

### Objective
Learn how to filter and retrieve relevant records from a dataset using Pandas Boolean conditions.

### Tools Used
- Python
- Pandas
- Jupyter Notebook

### Dataset
Student Performance Dataset

In [2]:
import pandas as pd

print("Pandas imported successfully!")

Pandas imported successfully!

In [3]:
data = {
    "Student_ID": range(1, 16),
    "Name": [
        "Aarav", "Priya", "Rahul", "Sneha", "Arjun",
        "Ananya", "Rohan", "Kavya", "Vikram", "Neha",
        "Aditya", "Pooja", "Karan", "Isha", "Manish"
    ],
    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female",
        "Male", "Female", "Male", "Female", "Male"
    ],
    "Age": [
        20, 21, 19, 22, 20,
        21, 23, 20, 22, 19,
        21, 22, 20, 23, 21
    ],
    "Math_Score": [
        85, 92, 67, 78, 95,
        88, 72, 90, 65, 81,
        89, 76, 94, 70, 83
    ],
    "Science_Score": [
        82, 95, 70, 80, 91,
        85, 75, 93, 68, 79,
        87, 74, 96, 72, 84
    ],
    "Attendance": [
        92, 95, 78, 85, 98,
        91, 82, 96, 75, 88,
        94, 80, 97, 83, 90
    ]
}

df = pd.DataFrame(data)

df

    Student_ID    Name  Gender  Age  Math_Score  Science_Score  Attendance
0            1   Aarav    Male   20          85             82          92
1            2   Priya  Female   21          92             95          95
2            3   Rahul    Male   19          67             70          78
3            4   Sneha  Female   22          78             80          85
4            5   Arjun    Male   20          95             91          98
5            6  Ananya  Female   21          88             85          91
6            7   Rohan    Male   23          72             75          82
7            8   Kavya  Female   20          90             93          96
8            9  Vikram    Male   22          65             68          75
9           10    Neha  Female   19          81             79          88
10          11  Aditya    Male   21          89             87          94
11          12   Pooja  Female   22          76             74          80
12          13   Karan    Male   20          94             96          97
13          14    Isha  Female   23          70             72          83
14          15  Manish    Male   21          83             84          90

In [4]:
df["Math_Score"] > 80

0      True
1      True
2     False
3     False
4      True
5      True
6     False
7      True
8     False
9      True
10     True
11    False
12     True
13    False
14     True
Name: Math_Score, dtype: bool

In [5]:
high_attendance = df[df["Attendance"] > 90]

print("Students with Attendance above 90:")
display(high_attendance)

print("Number of records:", len(high_attendance))

Students with Attendance above 90:

    Student_ID    Name  Gender  Age  Math_Score  Science_Score  Attendance
0            1   Aarav    Male   20          85             82          92
1            2   Priya  Female   21          92             95          95
4            5   Arjun    Male   20          95             91          98
5            6  Ananya  Female   21          88             85          91
7            8   Kavya  Female   20          90             93          96
10          11  Aditya    Male   21          89             87          94
12          13   Karan    Male   20          94             96          97

Number of records: 7

In [6]:
high_performers = df[
    (df["Math_Score"] > 80) &
    (df["Attendance"] > 90)
]

print("Students with Math Score above 80 AND Attendance above 90:")
display(high_performers)

print("Number of records:", len(high_performers))

Students with Math Score above 80 AND Attendance above 90:

    Student_ID    Name  Gender  Age  Math_Score  Science_Score  Attendance
0            1   Aarav    Male   20          85             82          92
1            2   Priya  Female   21          92             95          95
4            5   Arjun    Male   20          95             91          98
5            6  Ananya  Female   21          88             85          91
7            8   Kavya  Female   20          90             93          96
10          11  Aditya    Male   21          89             87          94
12          13   Karan    Male   20          94             96          97

Number of records: 7

In [7]:
excellent_students = df[
    (df["Math_Score"] > 90) |
    (df["Science_Score"] > 90)
]

print("Students with Math Score above 90 OR Science Score above 90:")
display(excellent_students)

print("Number of records:", len(excellent_students))

Students with Math Score above 90 OR Science Score above 90:

    Student_ID   Name  Gender  Age  Math_Score  Science_Score  Attendance
1            2  Priya  Female   21          92             95          95
4            5  Arjun    Male   20          95             91          98
7            8  Kavya  Female   20          90             93          96
12          13  Karan    Male   20          94             96          97

Number of records: 4

In [8]:
female_high_attendance = df[
    (df["Gender"] == "Female") &
    (df["Attendance"] > 85)
]

print("Female students with Attendance above 85:")
display(female_high_attendance)

print("Number of records:", len(female_high_attendance))

Female students with Attendance above 85:

   Student_ID    Name  Gender  Age  Math_Score  Science_Score  Attendance
1           2   Priya  Female   21          92             95          95
5           6  Ananya  Female   21          88             85          91
7           8   Kavya  Female   20          90             93          96
9          10    Neha  Female   19          81             79          88

Number of records: 4

In [9]:
df["Gender"] == "Female"

0     False
1      True
2     False
3      True
4     False
5      True
6     False
7      True
8     False
9      True
10    False
11     True
12    False
13     True
14    False
Name: Gender, dtype: bool

In [10]:
df["Attendance"] > 85

0      True
1      True
2     False
3     False
4      True
5      True
6     False
7      True
8     False
9      True
10     True
11    False
12     True
13    False
14     True
Name: Attendance, dtype: bool

In [11]:
medium_math = df[
    (df["Math_Score"] >= 70) &
    (df["Math_Score"] <= 90)
]

print("Students with Math Score between 70 and 90:")
display(medium_math)

print("Number of records:", len(medium_math))

Students with Math Score between 70 and 90:

    Student_ID    Name  Gender  Age  Math_Score  Science_Score  Attendance
0            1   Aarav    Male   20          85             82          92
3            4   Sneha  Female   22          78             80          85
5            6  Ananya  Female   21          88             85          91
6            7   Rohan    Male   23          72             75          82
7            8   Kavya  Female   20          90             93          96
9           10    Neha  Female   19          81             79          88
10          11  Aditya    Male   21          89             87          94
11          12   Pooja  Female   22          76             74          80
13          14    Isha  Female   23          70             72          83
14          15  Manish    Male   21          83             84          90

Number of records: 10

In [12]:
medium_math = df[
    (df["Math_Score"] >= 70) &
    (df["Math_Score"] <= 90)
]

print("Students with Math Score between 70 and 90:")
display(medium_math)

print("Number of records:", len(medium_math))

Students with Math Score between 70 and 90:

    Student_ID    Name  Gender  Age  Math_Score  Science_Score  Attendance
0            1   Aarav    Male   20          85             82          92
3            4   Sneha  Female   22          78             80          85
5            6  Ananya  Female   21          88             85          91
6            7   Rohan    Male   23          72             75          82
7            8   Kavya  Female   20          90             93          96
9           10    Neha  Female   19          81             79          88
10          11  Aditya    Male   21          89             87          94
11          12   Pooja  Female   22          76             74          80
13          14    Isha  Female   23          70             72          83
14          15  Manish    Male   21          83             84          90

Number of records: 10

In [15]:
print("Original number of records:", len(df))
print("Attendance > 90:", len(high_attendance))
print("Math > 80 AND Attendance > 90:", len(high_performers))
print("Math > 90 OR Science > 90:", len(excellent_students))
print("Female AND Attendance > 85:", len(female_high_attendance))
print("Math Score between 70 and 90:", len(medium_math))

Original number of records: 15
Attendance > 90: 7
Math > 80 AND Attendance > 90: 7
Math > 90 OR Science > 90: 4
Female AND Attendance > 85: 4
Math Score between 70 and 90: 10